### ISSUE TITLE
Please Create a Pull Request to oxid_ce

### ISSUE THREAD

**Issue by suabo** [N3XT0R/OXID-DependencyManager#1]
First of all i have to say: **Good job**

But there is no need to handle dependencies by another module. If the module isn't installed the dependency check will fail. But i would like to see dependecies for OXID modules. It would be one step into the right direction.

Can you please create a pull request into `OXID-eSales/oxideshop_ce` (https://github.com/OXID-eSales/oxideshop_ce/)?

If you don't got the time or anything and like me to create a pull request on your code, just tell me.

**Comment by N3XT0R** [comment]
Hello Suabo, 
at first, thank you for your feedback. 

For v1.1.0 i had already planned  list the dependencies from a module in a seperated tab on the module page  (Notice: This feature is already in work since some days). 

When Version 1.1.0 will be stable i will think about a pull request into the OXID-Repository.
